#!/usr/bin/env python
import argparse
import os


def create_parser():
    parser = argparse.ArgumentParser(description='Unix command line tool wc')
    parser.add_argument("-c", "--byte_count", metavar="file_name", help="Counts the number of bytes in a file")
    parser.add_argument("-l", "--line_count", metavar="file_name", help="Counts the number of lines in a file")
    return parser

def byte_count(file_path):
    if os.path.exists(f"./{file_path}"):
        file_size = os.path.getsize(f'./{file_path}')
        print(file_size, file_path)
    else:
        print(f"{file_path} does not exist in this root")
        
def line_count(file_path):
    if os.path.exists(f"./{file_path}"):
        with open(f"./{file_path}", "r") as file:
            count = sum(1 for line in file)
        print(count, file_path)
    else:
        print(f"{file_path} does not exist in this root")
    
def main():
    parser = create_parser()
    args = parser.parse_args()
    
    if args.byte_count:
        byte_count(args.byte_count)
    elif args.line_count:
        line_count(args.line_count)
        
if __name__ == "__main__":
    main()
    